# Generated by Django 4.1.7 on 2023-03-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_user_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='prenom',
        ),
    ]
