# Generated by Django 3.2.12 on 2023-03-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Etudiant', 'verbose_name_plural': 'Etudiants'},
        ),
        migrations.AddField(
            model_name='etudiant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
