# Generated by Django 4.1.7 on 2023-03-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0002_alter_etudiant_options_etudiant_is_active'),
        ('connexion', '0002_auto_20230316_1517'),
    ]

    operations = [
    ]
